import React, { useState } from 'react';
import { FileText, FileDown, FileSpreadsheet, ChevronDown } from 'lucide-react';
import { useUserStore } from '../../store/userStore';

const ExportSummaryWidget: React.FC = () => {
  const [isExportMenuOpen, setIsExportMenuOpen] = useState(false);
  const { cvs } = useUserStore();

  const handleExport = (type: string) => {
    const data = type === 'csv' 
      ? `Type,Count\nCandidate CVs,${cvs.length}\nEmail Blocks,4\nTasks,7\nEvents,25\n` 
      : `Mock ${type.toUpperCase()} file content for TaskOrbit Summary.\n\nTotal CVs: ${cvs.length}\nTotal Tasks: 7`;
    
    const blob = new Blob([data], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `TaskOrbit_Export.${type}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // Calculate dynamic percentage based on CVs length (just for visual scaling effect)
  const cvPercentage = Math.min(100, Math.max(10, cvs.length * 15));
  const gradient = `conic-gradient(#6366F1 0% ${cvPercentage}%, #10B981 ${cvPercentage}% 85%, #e5e7eb 85% 100%)`;

  return (
    <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100 flex flex-col h-full">
      <div className="flex items-center space-x-2 mb-6">
        <FileText size={20} className="text-gray-700" />
        <h2 className="text-lg font-bold text-gray-800">Export Summary</h2>
      </div>

      <div className="flex flex-col md:flex-row gap-8 mb-8 flex-1">
        <div className="flex-1 space-y-3">
          <div className="flex justify-between items-center text-sm">
            <span className="text-gray-600">Candidate CVs</span>
            <span className="font-bold text-indigo-600">{cvs.length}</span>
          </div>
          <hr className="border-gray-50" />
          <div className="flex justify-between items-center text-sm">
            <span className="text-gray-600">Total Email Blocks</span>
            <span className="font-medium">4</span>
          </div>
          <hr className="border-gray-50" />
          <div className="flex justify-between items-center text-sm">
            <span className="text-gray-600">Total Tasks</span>
            <span className="font-medium">7</span>
          </div>
          <hr className="border-gray-50" />
          <div className="flex justify-between items-center text-sm">
            <span className="text-gray-600">Total Events</span>
            <span className="font-medium">25</span>
          </div>
          <hr className="border-gray-50" />
          <div className="flex justify-between items-center text-sm">
            <span className="text-gray-600">Generated On</span>
            <span className="font-medium">{new Date().toLocaleDateString()}</span>
          </div>
          <hr className="border-gray-50" />
          <div className="flex justify-between items-center text-sm">
            <span className="text-gray-600">Generated By</span>
            <span className="font-medium">Admin</span>
          </div>
        </div>

        <div className="w-full sm:w-64 flex items-center justify-center">
          <div className="w-full h-full min-h-[180px] bg-white rounded-xl p-5 flex flex-col justify-between relative shadow-sm border border-gray-100 overflow-hidden group">
            {/* Background Grid Pattern */}
            <div className="absolute inset-0 opacity-[0.15] pointer-events-none" style={{ backgroundImage: 'linear-gradient(to right, #9ca3af 1px, transparent 1px), linear-gradient(to bottom, #9ca3af 1px, transparent 1px)', backgroundSize: '16px 16px' }}></div>
            
            {/* Header */}
            <div className="relative z-10 flex justify-between items-center mb-2">
              <span className="text-xs font-bold text-gray-400 uppercase tracking-wider">Analytics</span>
              <span className="text-[10px] bg-emerald-50 text-emerald-600 border border-emerald-100 px-2 py-0.5 rounded-full font-bold shadow-sm">Live</span>
            </div>

            {/* Charts Container */}
            <div className="relative z-10 flex items-end justify-between h-28 mt-auto px-1">
              {/* Donut Chart */}
              <div className="relative flex flex-col justify-end h-full">
                <div className="w-14 h-14 rounded-full shadow-md relative overflow-hidden transition-transform duration-500 hover:scale-105 cursor-pointer ring-2 ring-white" style={{ background: gradient }}>
                  <div className="absolute inset-[4px] rounded-full bg-white shadow-inner flex flex-col items-center justify-center">
                    <span className="text-[10px] font-bold text-indigo-600 leading-tight">{cvs.length}</span>
                    <span className="text-[6px] font-bold text-gray-400 uppercase tracking-wider leading-none">CVs</span>
                  </div>
                </div>
              </div>
              
              {/* Bar Charts (Scaled dynamically based on CV data for visual effect) */}
              <div className="flex items-end space-x-3 h-full pb-1">
                <div className="group cursor-pointer flex flex-col items-center">
                  <span className="text-[10px] text-gray-400 font-medium opacity-0 group-hover:opacity-100 transition-opacity mb-1 -translate-y-1">Q1</span>
                  <div className="w-4 bg-gradient-to-t from-blue-600 to-blue-400 rounded-sm shadow-sm transition-all duration-300 group-hover:shadow-md group-hover:-translate-y-0.5" style={{ height: `${Math.min(48, cvs.length * 8 + 10)}px` }}></div>
                </div>
                <div className="group cursor-pointer flex flex-col items-center">
                  <span className="text-[10px] text-gray-400 font-medium opacity-0 group-hover:opacity-100 transition-opacity mb-1 -translate-y-1">Q2</span>
                  <div className="w-4 bg-gradient-to-t from-emerald-500 to-emerald-300 rounded-sm shadow-sm transition-all duration-300 group-hover:shadow-md group-hover:-translate-y-0.5" style={{ height: `${Math.min(80, cvs.length * 15 + 20)}px` }}></div>
                </div>
                <div className="group cursor-pointer flex flex-col items-center">
                  <span className="text-[10px] text-gray-400 font-medium opacity-0 group-hover:opacity-100 transition-opacity mb-1 -translate-y-1">Q3</span>
                  <div className="w-4 bg-gradient-to-t from-indigo-500 to-indigo-300 rounded-sm shadow-sm transition-all duration-300 group-hover:shadow-md group-hover:-translate-y-0.5" style={{ height: `${Math.min(40, cvs.length * 5 + 15)}px` }}></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div className="relative inline-block text-left mt-auto">
        <button 
          onClick={() => setIsExportMenuOpen(!isExportMenuOpen)}
          className="flex items-center justify-center space-x-2 w-full sm:w-auto px-5 py-2.5 border border-gray-200 rounded-lg text-sm text-gray-700 bg-white hover:bg-gray-50 hover:border-gray-300 transition-all font-medium shadow-sm focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
        >
          <span>Export Options</span>
          <ChevronDown size={16} className={`text-gray-500 transition-transform ${isExportMenuOpen ? 'rotate-180' : ''}`} />
        </button>

        {isExportMenuOpen && (
          <div className="absolute left-0 bottom-full mb-2 w-48 rounded-xl shadow-lg bg-white ring-1 ring-black ring-opacity-5 z-20 animate-fade-in origin-bottom-left">
            <div className="p-1.5" role="menu" aria-orientation="vertical">
              <button
                onClick={() => { handleExport('pdf'); setIsExportMenuOpen(false); }}
                className="w-full flex items-center space-x-3 px-3 py-2.5 text-sm text-gray-700 hover:bg-gray-50 hover:text-gray-900 rounded-lg transition-colors text-left"
                role="menuitem"
              >
                <FileText size={16} className="text-rose-500" />
                <span className="font-medium">Export as PDF</span>
              </button>
              <button
                onClick={() => { handleExport('xlsx'); setIsExportMenuOpen(false); }}
                className="w-full flex items-center space-x-3 px-3 py-2.5 text-sm text-gray-700 hover:bg-gray-50 hover:text-gray-900 rounded-lg transition-colors text-left"
                role="menuitem"
              >
                <FileSpreadsheet size={16} className="text-emerald-600" />
                <span className="font-medium">Export as Excel</span>
              </button>
              <button
                onClick={() => { handleExport('csv'); setIsExportMenuOpen(false); }}
                className="w-full flex items-center space-x-3 px-3 py-2.5 text-sm text-gray-700 hover:bg-gray-50 hover:text-gray-900 rounded-lg transition-colors text-left"
                role="menuitem"
              >
                <FileDown size={16} className="text-indigo-600" />
                <span className="font-medium">Export as CSV</span>
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default ExportSummaryWidget;
