import React from 'react';
import { FileText, FileDown, FileSpreadsheet } from 'lucide-react';

const ExportSummaryWidget: React.FC = () => {
  const handleExport = (type: string) => {
    const data = type === 'csv' 
      ? "Type,Count\nSticky Notes,6\nEmail Blocks,4\nTasks,7\nEvents,25\n" 
      : `Mock ${type.toUpperCase()} file content for TaskOrbit Summary.\n\nTotal Tasks: 7\nCompleted: 2`;
    
    const blob = new Blob([data], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `TaskOrbit_Export.${type}`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100 flex flex-col h-full">
      <div className="flex items-center space-x-2 mb-6">
        <FileText size={20} className="text-gray-700" />
        <h2 className="text-lg font-bold text-gray-800">Export Summary</h2>
      </div>

      <div className="flex flex-col md:flex-row gap-8 mb-8 flex-1">
        <div className="flex-1 space-y-3">
          <div className="flex justify-between items-center text-sm">
            <span className="text-gray-600">Total Sticky Notes</span>
            <span className="font-medium">6</span>
          </div>
          <hr className="border-gray-50" />
          <div className="flex justify-between items-center text-sm">
            <span className="text-gray-600">Total Email Blocks</span>
            <span className="font-medium">4</span>
          </div>
          <hr className="border-gray-50" />
          <div className="flex justify-between items-center text-sm">
            <span className="text-gray-600">Total Tasks</span>
            <span className="font-medium">7</span>
          </div>
          <hr className="border-gray-50" />
          <div className="flex justify-between items-center text-sm">
            <span className="text-gray-600">Completed Tasks</span>
            <span className="font-medium">2</span>
          </div>
          <hr className="border-gray-50" />
          <div className="flex justify-between items-center text-sm">
            <span className="text-gray-600">Total Events</span>
            <span className="font-medium">25</span>
          </div>
          <hr className="border-gray-50" />
          <div className="flex justify-between items-center text-sm">
            <span className="text-gray-600">Generated On</span>
            <span className="font-medium">May 21, 2025 11:30 AM</span>
          </div>
          <hr className="border-gray-50" />
          <div className="flex justify-between items-center text-sm">
            <span className="text-gray-600">Generated By</span>
            <span className="font-medium">Admin</span>
          </div>
        </div>

        <div className="w-48 flex items-center justify-center">
          <div className="w-full h-full min-h-[160px] bg-gray-50 rounded-lg p-4 flex flex-col justify-end relative shadow-inner border border-gray-100">
            {/* Dummy chart graphic */}
            <div className="absolute top-4 left-4 right-4 h-2 bg-gray-200 rounded-full"></div>
            <div className="absolute top-8 left-4 right-8 h-2 bg-gray-200 rounded-full"></div>
            <div className="absolute top-12 left-4 right-12 h-2 bg-gray-200 rounded-full"></div>
            
            <div className="flex items-end justify-between h-20 space-x-2 mt-auto">
              <div className="w-8 h-8 rounded-full bg-[#FF9800] shrink-0 border-2 border-white shadow-sm self-end mb-1 z-10" style={{ clipPath: 'polygon(50% 50%, 100% 0, 100% 100%, 0 100%, 0 0)'}}></div>
              <div className="w-3 h-10 bg-blue-400 rounded-t-sm"></div>
              <div className="w-3 h-14 bg-green-400 rounded-t-sm"></div>
              <div className="w-3 h-8 bg-blue-600 rounded-t-sm"></div>
            </div>
          </div>
        </div>
      </div>

      <div className="flex flex-wrap gap-3">
        <button 
          onClick={() => handleExport('pdf')}
          className="flex items-center space-x-2 px-4 py-2 border border-gray-200 rounded text-sm text-gray-700 hover:bg-gray-50 transition-colors"
        >
          <FileText size={16} className="text-red-500" />
          <span>Export as PDF</span>
        </button>
        <button 
          onClick={() => handleExport('xlsx')}
          className="flex items-center space-x-2 px-4 py-2 border border-gray-200 rounded text-sm text-gray-700 hover:bg-gray-50 transition-colors"
        >
          <FileSpreadsheet size={16} className="text-green-600" />
          <span>Export as Excel</span>
        </button>
        <button 
          onClick={() => handleExport('csv')}
          className="flex items-center space-x-2 px-4 py-2 border border-gray-200 rounded text-sm text-gray-700 hover:bg-gray-50 transition-colors"
        >
          <FileDown size={16} className="text-[#051C45]" />
          <span>Export as CSV</span>
        </button>
      </div>
    </div>
  );
};

export default ExportSummaryWidget;
